 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Bubble Dancer RES                                           
     # Surfaces =   5
     # Strips   =  83
     # Vortices = 484

  Sref =  1000.0       Cref =  10.000       Bref =  116.60    
  Xref =  3.4000       Yref =  0.0000       Zref = 0.50000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.02577     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.05778
  CZtot =  -0.58445     Cntot =   0.00000     Cn'tot =  -0.00000

  CLtot =   0.58447
  CDtot =   0.02526
  CDvis =   0.01700     CDind = 0.0082638
  CLff  =   0.58284     CDff  = 0.0081435    | Trefftz
  CYff  =   0.00000         e =    0.9767    | Plane  

   flap            =   0.00000
   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.631072    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.383451
 x  force CD |    CDa =   0.161472    CDb =  -0.000000
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.232642
 y  mom.  Cm |    Cma =  -0.938373    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.061288

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   7.447111    CLr =   0.000000
 y  force CY |    CYp =  -0.411865    CYq =   0.000000    CYr =   0.272834
 x  force CD |    CDp =  -0.000000    CDq =   0.171416    CDr =   0.000000
 x' mom.  Cl'|    Clp =  -0.632074    Clq =   0.000000    Clr =   0.144929
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -12.174270    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.056987    Cnq =   0.000000    Cnr =  -0.064182

                  flap         d01     aileron      d02     elevator     d03     rudder       d04 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.019376   CLd02 =  -0.000000   CLd03 =   0.008018   CLd04 =   0.000000
 y  force CY |   CYd01 =   0.000000   CYd02 =   0.000038   CYd03 =  -0.000000   CYd04 =  -0.003340
 x  force CD |   CDd01 =   0.000602   CDd02 =   0.000000   CDd03 =   0.000407   CDd04 =  -0.000000
 x' mom.  Cl'|   Cld01 =   0.000000   Cld02 =   0.000048   Cld03 =   0.000000   Cld04 =   0.000029
 y  mom.  Cm |   Cmd01 =   0.004703   Cmd02 =   0.000000   Cmd03 =  -0.027294   Cmd04 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000000   Cnd02 =  -0.000003   Cnd03 =   0.000000   Cnd04 =   0.001234
 Trefftz drag| CDffd01 =   0.000597 CDffd02 =   0.000000 CDffd03 =   0.000406 CDffd04 =   0.000000
 span eff.   |    ed01 =  -0.006994    ed02 =  -0.000000    ed03 =  -0.021718    ed04 =  -0.000000



 Neutral point  Xnp =   5.066419

 Clb Cnr / Clr Cnb  =   1.681007    (  > 1 if spirally stable )
